# Use postgres/example user/password credentials
version: "3.1"

services:
  db-electiva2:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "electiva2"
      POSTGRES_USER: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
