# Use postgres/example user/password credentials
version: "3.8"

services:
  db:
    build: ./database
    restart: always
    ports:
      - "5432:5432"
    hostname: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - mynet
  faker-python:
    build: ./faker
    volumes:
      - ./faker:/usr/src/app
    ports:
      - "3005:3005"
volumes:
  database_data:
    driver: local
networks:
  mynet:
    name: my-shared-db-network
