# Use postgres/example user/password credentials
version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: electiva2
      POSTGRES_USER: root
      POSTGRES_DB: products
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet
  faker-python:
    build: ./faker
    volumes:
      - ./faker:/usr/src/app
    ports:
      - "3005:3005"
volumes:
  database_data:
    driver: local
networks:
  mynet:
    name: my-shared-db-network
